// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `userfile.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.qingzhenyun.common.ice.userfile;

public class FileOperationException extends com.qingzhenyun.common.ice.common.CommonRpcException
{
    public FileOperationException()
    {
        super();
    }

    public FileOperationException(Throwable cause)
    {
        super(cause);
    }

    public FileOperationException(int innerCode, String innerMessage, int fileType)
    {
        super(innerCode, innerMessage);
        this.fileType = fileType;
    }

    public FileOperationException(int innerCode, String innerMessage, int fileType, Throwable cause)
    {
        super(innerCode, innerMessage, cause);
        this.fileType = fileType;
    }

    public String ice_id()
    {
        return "::userfile::FileOperationException";
    }

    public int fileType;

    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::userfile::FileOperationException", -1, false);
        ostr_.writeInt(fileType);
        ostr_.endSlice();
        super._writeImpl(ostr_);
    }

    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        fileType = istr_.readInt();
        istr_.endSlice();
        super._readImpl(istr_);
    }

    public static final long serialVersionUID = -4385438827145581631L;
}
