// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `userfile.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.qingzhenyun.common.ice.userfile;

public class UserAsyncTask extends com.zeroc.Ice.Value
{
    public UserAsyncTask()
    {
        this.uuid = "";
        this.destUuid = "";
    }

    public UserAsyncTask(long userId, String uuid, String destUuid, int type, long createTime)
    {
        this.userId = userId;
        this.uuid = uuid;
        this.destUuid = destUuid;
        this.type = type;
        this.createTime = createTime;
    }

    public long userId;

    public String uuid;

    public String destUuid;

    public int type;

    public long createTime;

    public UserAsyncTask clone()
    {
        return (UserAsyncTask)super.clone();
    }

    public static String ice_staticId()
    {
        return "::userfile::UserAsyncTask";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    public static final long serialVersionUID = 3478657503434412904L;

    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeLong(userId);
        ostr_.writeString(uuid);
        ostr_.writeString(destUuid);
        ostr_.writeInt(type);
        ostr_.writeLong(createTime);
        ostr_.endSlice();
    }

    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        userId = istr_.readLong();
        uuid = istr_.readString();
        destUuid = istr_.readString();
        type = istr_.readInt();
        createTime = istr_.readLong();
        istr_.endSlice();
    }
}
