// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `userfile.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.qingzhenyun.common.ice.userfile;

public class UserFileResponse extends com.zeroc.Ice.Value
{
    public UserFileResponse()
    {
        this.uuid = "";
        this.storeId = "";
        this.path = "";
        this.name = "";
        this.ext = "";
        this.parent = "";
    }

    public UserFileResponse(String uuid, String storeId, long userId, String path, String name, String ext, long size, String parent, int type, long atime, long ctime, long mtime, int version, boolean locking, int opt)
    {
        this.uuid = uuid;
        this.storeId = storeId;
        this.userId = userId;
        this.path = path;
        this.name = name;
        this.ext = ext;
        this.size = size;
        this.parent = parent;
        this.type = type;
        this.atime = atime;
        this.ctime = ctime;
        this.mtime = mtime;
        this.version = version;
        this.locking = locking;
        this.opt = opt;
    }

    public String uuid;

    public String storeId;

    public long userId;

    public String path;

    public String name;

    public String ext;

    public long size;

    public String parent;

    public int type;

    public long atime;

    public long ctime;

    public long mtime;

    public int version;

    public boolean locking;

    public int opt;

    public UserFileResponse clone()
    {
        return (UserFileResponse)super.clone();
    }

    public static String ice_staticId()
    {
        return "::userfile::UserFileResponse";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    public static final long serialVersionUID = 7397492762507671988L;

    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeString(uuid);
        ostr_.writeString(storeId);
        ostr_.writeLong(userId);
        ostr_.writeString(path);
        ostr_.writeString(name);
        ostr_.writeString(ext);
        ostr_.writeLong(size);
        ostr_.writeString(parent);
        ostr_.writeInt(type);
        ostr_.writeLong(atime);
        ostr_.writeLong(ctime);
        ostr_.writeLong(mtime);
        ostr_.writeInt(version);
        ostr_.writeBool(locking);
        ostr_.writeInt(opt);
        ostr_.endSlice();
    }

    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        uuid = istr_.readString();
        storeId = istr_.readString();
        userId = istr_.readLong();
        path = istr_.readString();
        name = istr_.readString();
        ext = istr_.readString();
        size = istr_.readLong();
        parent = istr_.readString();
        type = istr_.readInt();
        atime = istr_.readLong();
        ctime = istr_.readLong();
        mtime = istr_.readLong();
        version = istr_.readInt();
        locking = istr_.readBool();
        opt = istr_.readInt();
        istr_.endSlice();
    }
}
