// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `common.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function (module, require, exports) {
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let common = _ModuleRegistry.module("common");

    const iceC_common_CommonPage_ids = [
        "::Ice::Object",
        "::common::CommonPage"
    ];

    common.CommonPage = class extends Ice.Value {
        constructor(page = 0, pageSize = 0, totalCount = 0, totalPage = 0) {
            super();
            this.page = page;
            this.pageSize = pageSize;
            this.totalCount = totalCount;
            this.totalPage = totalPage;
        }

        _iceWriteMemberImpl(ostr) {
            ostr.writeInt(this.page);
            ostr.writeInt(this.pageSize);
            ostr.writeInt(this.totalCount);
            ostr.writeInt(this.totalPage);
        }

        _iceReadMemberImpl(istr) {
            this.page = istr.readInt();
            this.pageSize = istr.readInt();
            this.totalCount = istr.readInt();
            this.totalPage = istr.readInt();
        }
    };

    Slice.defineValue(common.CommonPage, iceC_common_CommonPage_ids[1], false);

    common.CommonPageDisp = class extends Ice.Object {
    };

    Slice.defineOperations(common.CommonPageDisp, undefined, iceC_common_CommonPage_ids, 1);

    common.CommonRpcException = class extends Ice.UserException {
        constructor(innerCode = 0, innerMessage = "", _cause = "") {
            super(_cause);
            this.innerCode = innerCode;
            this.innerMessage = innerMessage;
        }

        static get _parent() {
            return Ice.UserException;
        }

        static get _id() {
            return "::common::CommonRpcException";
        }

        _mostDerivedType() {
            return common.CommonRpcException;
        }

        _writeMemberImpl(ostr) {
            ostr.writeInt(this.innerCode);
            ostr.writeString(this.innerMessage);
        }

        _readMemberImpl(istr) {
            this.innerCode = istr.readInt();
            this.innerMessage = istr.readString();
        }
    };

    Slice.defineSequence(common, "StringListHelper", "Ice.StringHelper", false);
    exports.common = common;
};
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
    typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : this.Ice._require,
    typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : this)
)
;
