// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `common.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.qingzhenyun.common.ice.common;

public class CommonPage extends com.zeroc.Ice.Value {
    public static final long serialVersionUID = -3080956421140362601L;
    public int page;
    public int pageSize;
    public int totalCount;
    public int totalPage;

    public CommonPage() {
    }

    public CommonPage(int page, int pageSize, int totalCount, int totalPage) {
        this.page = page;
        this.pageSize = pageSize;
        this.totalCount = totalCount;
        this.totalPage = totalPage;
    }

    public static String ice_staticId() {
        return "::common::CommonPage";
    }

    public CommonPage clone() {
        return (CommonPage) super.clone();
    }

    @Override
    public String ice_id() {
        return ice_staticId();
    }

    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_) {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeInt(page);
        ostr_.writeInt(pageSize);
        ostr_.writeInt(totalCount);
        ostr_.writeInt(totalPage);
        ostr_.endSlice();
    }

    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_) {
        istr_.startSlice();
        page = istr_.readInt();
        pageSize = istr_.readInt();
        totalCount = istr_.readInt();
        totalPage = istr_.readInt();
        istr_.endSlice();
    }
}
