// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `common.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.qingzhenyun.common.ice.common;

public class CommonRpcException extends com.zeroc.Ice.UserException {
    public static final long serialVersionUID = -6698224072596681125L;
    public int innerCode;
    public String innerMessage;

    public CommonRpcException() {
        this.innerMessage = "";
    }

    public CommonRpcException(Throwable cause) {
        super(cause);
        this.innerMessage = "";
    }

    public CommonRpcException(int innerCode, String innerMessage) {
        this.innerCode = innerCode;
        this.innerMessage = innerMessage;
    }

    public CommonRpcException(int innerCode, String innerMessage, Throwable cause) {
        super(cause);
        this.innerCode = innerCode;
        this.innerMessage = innerMessage;
    }

    public String ice_id() {
        return "::common::CommonRpcException";
    }

    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_) {
        ostr_.startSlice("::common::CommonRpcException", -1, true);
        ostr_.writeInt(innerCode);
        ostr_.writeString(innerMessage);
        ostr_.endSlice();
    }

    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_) {
        istr_.startSlice();
        innerCode = istr_.readInt();
        innerMessage = istr_.readString();
        istr_.endSlice();
    }
}
